### PR TITLE
BorderRadius 10 for windows and macos

### PR DESCRIPTION
**Pull request by chzappsinc**

### CODE REVIEW

**Comment by aminebenkeroum** [comment]
Can you please show us how it looks? I have an idea but i want to see before merging

**Comment by chzappsinc** [comment]
**Before**
image

**After** 
image

Also, look at the inner circle position on large dimensions

**Comment by chzappsinc** [comment]
Updated

**Comment by chzappsinc** [comment]
image

**Comment by chzappsinc** [comment]
image

Full screen

**Comment by chzappsinc** [comment]
Did you merge it?

**Pull request merged**
